export const destinations = [
  { name: 'Hampi', region: 'Karnataka', category: 'History', rating: '4.9', description: 'Stone ruins, wild boulders and slow afternoons beside the Tungabhadra.', budget: '₹18,000', crowd: 'Moderate', latitude: 15.335, longitude: 76.46, image: 'https://images.unsplash.com/photo-1600100397608-f0107f7d5a35?auto=format&fit=crop&w=900&q=85' },
  { name: 'Araku Valley', region: 'Andhra Pradesh', category: 'Nature', rating: '4.8', description: 'Misty coffee country where mountain trains and forest trails meet.', budget: '₹14,500', crowd: 'Low', latitude: 18.327, longitude: 82.874, image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85' },
  { name: 'Jaipur', region: 'Rajasthan', category: 'Popular', rating: '4.7', description: 'Rose-coloured streets, generous food and a living royal legacy.', budget: '₹16,000', crowd: 'High', latitude: 26.912, longitude: 75.787, image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=85' },
  { name: 'Kerala', region: 'Kerala', category: 'Nature', rating: '4.9', description: 'Backwaters, spice gardens and coastlines made for taking your time.', budget: '₹22,000', crowd: 'Moderate', latitude: 9.931, longitude: 76.267, image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=85' },
  { name: 'Meghalaya', region: 'Northeast India', category: 'Adventure', rating: '4.9', description: 'Living root bridges, cloud forests and rain that makes everything glow.', budget: '₹24,000', crowd: 'Low', latitude: 25.467, longitude: 91.366, image: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=900&q=85' },
  { name: 'Varanasi', region: 'Uttar Pradesh', category: 'Culture', rating: '4.6', description: 'Ancient ghats, morning light and a city that rewards curiosity.', budget: '₹12,000', crowd: 'High', latitude: 25.317, longitude: 82.973, image: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=900&q=85' },
  { name: 'Udaipur', region: 'Rajasthan', category: 'Popular', rating: '4.8', description: 'Lakeside mornings, blue hour balconies and unhurried old-world charm.', budget: '₹17,500', crowd: 'Moderate', latitude: 24.585, longitude: 73.712, image: 'https://images.unsplash.com/photo-1602643163983-ed0babc39797?auto=format&fit=crop&w=900&q=85' },
  { name: 'Goa', region: 'Goa', category: 'Food', rating: '4.7', description: 'Sunlit villages, small kitchens and a coastline with its own rhythm.', budget: '₹20,000', crowd: 'High', latitude: 15.299, longitude: 74.124, image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=85' },
]

export const destinationBySlug = (slug) => destinations.find((destination) => destination.name.toLowerCase().replaceAll(' ', '-') === slug)

export const gems = [
  { place: 'Chettinad', location: 'Tamil Nadu', why: 'Mansions, hand-painted tiles and some of South India’s most generous food.', best: 'November – February', crowd: 'Very low', budget: '₹15,000', experience: 'A heritage home lunch', tag: 'Culture', image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=900&q=85' },
  { place: 'Chopta', location: 'Uttarakhand', why: 'A quiet Himalayan meadow with big mountain views and clear night skies.', best: 'March – June', crowd: 'Low', budget: '₹13,500', experience: 'A guided forest trek', tag: 'Nature', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85' },
  { place: 'Majuli', location: 'Assam', why: 'River-island calm, mask-making traditions and a culture unlike anywhere else.', best: 'October – April', crowd: 'Very low', budget: '₹16,500', experience: 'Meet a mask artisan', tag: 'Culture', image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85' },
  { place: 'Gurez Valley', location: 'Kashmir', why: 'Wild valleys and warm village stays far from the usual Kashmir circuit.', best: 'May – September', crowd: 'Low', budget: '₹21,000', experience: 'A night in a wooden homestay', tag: 'Adventure', image: 'https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=900&q=85' },
]

export const experiences = [
  { type: 'Local Guide', name: 'Old City, New Stories', provider: 'Meera’s Jaipur Walks', location: 'Jaipur, Rajasthan', rating: '4.9', price: '₹850 / person', description: 'Follow a local storyteller through lanes, courtyards and family-run workshops.', image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=85' },
  { type: 'Homestay', name: 'The Mango Orchard Stay', provider: 'Anita & family', location: 'Sakleshpur, Karnataka', rating: '4.8', price: '₹2,400 / night', description: 'Wake to birdsong, estate coffee and a table set with food from the garden.', image: 'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=900&q=85' },
  { type: 'Local Restaurant', name: 'A Table at Home', provider: 'Ramesh’s Kitchen', location: 'Kochi, Kerala', rating: '4.9', price: '₹1,200 / person', description: 'A warm, intimate meal of recipes passed through three generations.', image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=85' },
  { type: 'Handicrafts', name: 'Clay & Quiet', provider: 'The Potter Collective', location: 'Khurja, Uttar Pradesh', rating: '4.7', price: '₹650 / person', description: 'Make something useful with your hands and meet the makers behind the craft.', image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=900&q=85' },
  { type: 'Cooking Class', name: 'Spice Route Supper', provider: 'Lakshmi’s Table', location: 'Munnar, Kerala', rating: '5.0', price: '₹1,500 / person', description: 'Shop, cook and sit down to a fragrant meal in a family kitchen.', image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=85' },
  { type: 'Cultural Workshop', name: 'A Rhythm of Dhol', provider: 'Swarang Studio', location: 'Ahmedabad, Gujarat', rating: '4.8', price: '₹900 / person', description: 'Learn the heartbeat of a folk tradition from the artists keeping it alive.', image: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?auto=format&fit=crop&w=900&q=85' },
  { type: 'Adventure Activity', name: 'River, Rock, Repeat', provider: 'Wild South Collective', location: 'Dandeli, Karnataka', rating: '4.9', price: '₹2,200 / person', description: 'A guided day of river rapids, forest paths and a picnic in the wild.', image: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=900&q=85' },
]
