import { useState } from 'react'
import DayPlanMap from './components/DayPlanMap.jsx'

function directionsUrl(place) { return `https://www.google.com/maps/dir/?api=1&destination=${place.latitude},${place.longitude}` }
function readableDate(date) { return date ? new Date(`${date}T12:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Your selected day' }

function MyDayPlan({ plan, onNavigate }) {
  const [focusedPlace, setFocusedPlace] = useState(null)
  if (!plan) return <main className="simple-route-page"><section className="simple-route-card"><p className="section-kicker">No plan yet</p><h1>Let’s shape your day.</h1><button className="primary-button" type="button" onClick={() => onNavigate('/day-planner')}>Plan My Day</button></section></main>
  return <main className="day-plan-page"><nav className="nav-shell day-plan-nav"><button className="back-link destination-back" type="button" onClick={() => onNavigate('/day-planner', plan)}>← <span>Edit plan</span></button><a className="brand" href="/" onClick={(event) => { event.preventDefault(); onNavigate('/') }}><span className="brand-mark">Y</span><span>Yatra<span className="brand-accent">AI</span></span></a></nav><header className="day-plan-header"><div><p className="eyebrow"><span></span> Your considered day</p><h1>My Day <em>Plan.</em></h1><p>From first light to the last table, shaped around your way of travelling.</p></div><div className="day-plan-summary"><strong>{plan.destination}</strong><span>{readableDate(plan.date)}</span><span>{plan.budget} budget · {plan.interests.join(', ')}</span></div></header><section className="day-plan-overview"><div><span>Starting from</span><strong>{plan.hotel}</strong></div><div><span>Travel distance</span><strong>{plan.totalDistance} km</strong></div><div><span>Travel time</span><strong>{plan.totalTravelMinutes} min</strong></div><div><span>Estimated total</span><strong>₹{plan.totalCost.toLocaleString('en-IN')}</strong></div></section><section className="day-plan-layout"><div className="day-plan-timeline"><div className="section-title-row"><h2>From morning<br /><em>to evening.</em></h2><span>8:00 AM — 8:00 PM</span></div><div className="meal-strip">{plan.meals.map((meal) => <div key={meal.label}><span>{meal.time}</span><strong>{meal.label}</strong><small>{meal.name}</small></div>)}</div>{plan.places.map((place, index) => <article className={focusedPlace?.name === place.name ? 'day-stop focused' : 'day-stop'} key={place.name} onClick={() => setFocusedPlace(place)}><div className="day-stop-time">{place.time}</div><div className="day-stop-marker">{index + 1}</div><div className="day-stop-body"><img src={place.image} alt={`${place.name} destination`} /><div><p className="section-kicker">{place.type}</p><h3>{place.name}</h3><p>{place.description}</p><div className="day-stop-meta"><span>{place.duration} min</span><span>{place.fee ? `₹${place.fee} entry` : 'Free entry'}</span><span>{place.travelToNext ? `${place.travelToNext} km to next` : 'Final stop'}</span></div><a className="text-link" href={directionsUrl(place)} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()}>Get Directions <span>↗</span></a></div></div></article>)}</div><aside className="day-plan-map-panel"><div className="map-panel-heading"><p className="section-kicker">Your route</p><h2>Follow the <em>golden thread.</em></h2></div><DayPlanMap places={plan.places} focusedPlace={focusedPlace} /></aside></section></main>
}

export default MyDayPlan
